// This file is auto-generated to ensure all project mdi icons are registered.
// Do not edit manually unless updating icon usage.
import {
  mdiAccount,
  mdiAccountBoxMultipleOutline,
  mdiAccountBoxOutline,
  mdiAccountCircleOutline,
  mdiAccountCog,
  mdiAccountCogOutline,
  mdiAccountGroup,
  mdiAccountGroupOutline,
  mdiAccountHeartOutline,
  mdiAccountKey,
  mdiAccountMultiple,
  mdiAccountMultipleCheckOutline,
  mdiAccountMultipleOutline,
  mdiAccountOutline,
  mdiAccountPlus,
  mdiAccountPlusOutline,
  mdiAccountQuestionOutline,
  mdiAccountTie,
  mdiAccountVoice,
  mdiAlertCircle,
  mdiAlertDecagram,
  mdiAlertDecagramOutline,
  mdiApi,
  mdiAppleKeyboardCommand,
  mdiAppleKeyboardControl,
  mdiAppleKeyboardOption,
  mdiAppleKeyboardShift,
  mdiArrowDown,
  mdiArrowDownBold,
  mdiArrowLeft,
  mdiArrowRight,
  mdiArrowTopRight,
  mdiArrowUp,
  mdiArrowUpBold,
  mdiBackspace,
  mdiBasketball,
  mdiBellOutline,
  mdiBellPlusOutline,
  mdiBellRing,
  mdiBookOpenOutline,
  mdiBookOpenPageVariant,
  mdiBookOpenPageVariantOutline,
  mdiBriefcaseAccountOutline,
  mdiBriefcaseOutline,
  mdiBriefcaseSearch,
  mdiBriefcaseSearchOutline,
  mdiBriefcaseVariant,
  mdiBugOutline,
  mdiBullhorn,
  mdiBullhornOutline,
  mdiCached,
  mdiCalendar,
  mdiCalendarBlank,
  mdiCalendarCheck,
  mdiCalendarClock,
  mdiCalendarStart,
  mdiCardAccountDetailsOutline,
  mdiCart,
  mdiCartOutline,
  mdiCartOff,
  mdiCashMultiple,
  mdiCashSync,
  mdiCertificateOutline,
  mdiChartAreaspline,
  mdiChartBellCurve,
  mdiChartBoxOutline,
  mdiChartLineVariant,
  mdiChartTimelineVariant,
  mdiChatOutline,
  mdiChatProcessingOutline,
  mdiCheck,
  mdiCheckCircle,
  mdiCheckCircleOutline,
  mdiCheckDecagram,
  mdiCheckboxBlankCircleOutline,
  mdiCheckboxBlankOutline,
  mdiCheckboxMarked,
  mdiCheckboxMarkedCircleOutline,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiCircle,
  mdiClipboardCheck,
  mdiClipboardCheckOutline,
  mdiClipboardPlus,
  mdiClipboardText,
  mdiClipboardTextClockOutline,
  mdiClipboardTextOutline,
  mdiClockFast,
  mdiClockOutline,
  mdiClose,
  mdiCloseCircle,
  mdiCloudUpload,
  mdiCogOutline,
  mdiCompassOutline,
  mdiConnection,
  mdiContentSave,
  mdiContentSaveOutline,
  mdiControllerClassicOutline,
  mdiCreditCardCheckOutline,
  mdiCreditCardSync,
  mdiCropSquare,
  mdiCurrencyUsd,
  mdiDatabase,
  mdiDatabaseOutline,
  mdiDelete,
  mdiDeleteOutline,
  mdiDomain,
  mdiDotsGrid,
  mdiDotsHorizontal,
  mdiDotsVertical,
  mdiDownload,
  mdiEarth,
  mdiEarthPlus,
  mdiEmail,
  mdiEmailEditOutline,
  mdiEmailOutline,
  mdiEmoticonHappyOutline,
  mdiEmoticonSadOutline,
  mdiEye,
  mdiEyeCheckOutline,
  mdiEyeOff,
  mdiEyeOutline,
  mdiEyedropper,
  mdiFacebookMessenger,
  mdiFileChart,
  mdiFileDocument,
  mdiFileDocumentEdit,
  mdiFileDocumentEditOutline,
  mdiFileDocumentOutline,
  mdiFileDownloadOutline,
  mdiFilmstripBoxMultiple,
  mdiFlag,
  mdiFlagCheckered,
  mdiFlagOutline,
  mdiFlagVariantOutline,
  mdiFlash,
  mdiFolderAccount,
  mdiFormatAlignJustify,
  mdiFormatListChecks,
  mdiForumOutline,
  mdiFullscreen,
  mdiFullscreenExit,
  mdiGamepadVariantOutline,
  mdiGavel,
  mdiGithub,
  mdiGoogle,
  mdiHistory,
  mdiHomeMapMarker,
  mdiImageFilterHdr,
  mdiImageMultiple,
  mdiImageMultipleOutline,
  mdiImageOutline,
  mdiInformation,
  mdiInformationOutline,
  mdiKeyboardReturn,
  mdiKeyboardSpace,
  mdiKeyVariant,
  mdiLabelOutline,
  mdiLifebuoy,
  mdiLightbulbOnOutline,
  mdiLightningBolt,
  mdiLinkVariant,
  mdiLinkedin,
  mdiLoading,
  mdiLock,
  mdiLogin,
  mdiLogout,
  mdiMagnify,
  mdiMapMarker,
  mdiMapMarkerOutline,
  mdiMenu,
  mdiMenuDown,
  mdiMenuRight,
  mdiMessage,
  mdiMessageTextOutline,
  mdiMessageOutline,
  mdiMessagePlusOutline,
  mdiMessageProcessingOutline,
  mdiMessageReplyText,
  mdiMicrophone,
  mdiMicrosoft,
  mdiMinus,
  mdiMinusBox,
  mdiMonitorDashboard,
  mdiMoviePlayOutline,
  mdiOpenInNew,
  mdiPageFirst,
  mdiPageLast,
  mdiPalette,
  mdiPaletteOutline,
  mdiPaperclip,
  mdiPause,
  mdiPencil,
  mdiPencilOutline,
  mdiPlay,
  mdiPlayCircle,
  mdiPlayCircleOutline,
  mdiPlaylistEdit,
  mdiPlaylistPlus,
  mdiPlus,
  mdiPostOutline,
  mdiProgressClock,
  mdiRadar,
  mdiRadioboxBlank,
  mdiRadioboxMarked,
  mdiRefresh,
  mdiReload,
  mdiRestore,
  mdiRhombusMedium,
  mdiRobotHappyOutline,
  mdiRobotOutline,
  mdiRocketLaunchOutline,
  mdiSchoolOutline,
  mdiScriptTextPlayOutline,
  mdiSend,
  mdiShapeOutline,
  mdiShareOutline,
  mdiShieldAccount,
  mdiShieldAccountOutline,
  mdiShieldAlert,
  mdiShieldCheck,
  mdiShieldCheckOutline,
  mdiShieldCrown,
  mdiShieldKey,
  mdiShieldLock,
  mdiShoppingOutline,
  mdiShoppingSearch,
  mdiSpeedometer,
  mdiSpeedometerMedium,
  mdiSquareEditOutline,
  mdiStar,
  mdiStarHalfFull,
  mdiStarOutline,
  mdiStoreOutline,
  mdiStorefrontOutline,
  mdiSubdirectoryArrowRight,
  mdiSvg,
  mdiTableArrowDown,
  mdiTag,
  mdiTagMultipleOutline,
  mdiTarget,
  mdiTextBoxEditOutline,
  mdiTextBoxMultiple,
  mdiTextBoxOutline,
  mdiThemeLightDark,
  mdiThumbUpOutline,
  mdiTimelineClockOutline,
  mdiTimerOff,
  mdiTimerSand,
  mdiTools,
  mdiTransitConnection,
  mdiTrophyOutline,
  mdiTune,
  mdiTwitter,
  mdiUnfoldMoreHorizontal,
  mdiUpdate,
  mdiVideo,
  mdiViewDashboardOutline,
  mdiViewGridOutline,
  mdiVolumeHigh,
  mdiVolumeLow,
  mdiVolumeMedium,
  mdiVolumeVariantOff,
  mdiWeatherNight,
  mdiWeatherSunny,
  mdiWhatsapp,
} from "@mdi/js";

export const fullProjectMdiIcons = {
  "mdi-account": mdiAccount,
  "mdi-account-box-multiple-outline": mdiAccountBoxMultipleOutline,
  "mdi-account-box-outline": mdiAccountBoxOutline,
  "mdi-account-circle-outline": mdiAccountCircleOutline,
  "mdi-account-cog": mdiAccountCog,
  "mdi-account-cog-outline": mdiAccountCogOutline,
  "mdi-account-group": mdiAccountGroup,
  "mdi-account-group-outline": mdiAccountGroupOutline,
  "mdi-account-heart-outline": mdiAccountHeartOutline,
  "mdi-account-key": mdiAccountKey,
  "mdi-account-multiple": mdiAccountMultiple,
  "mdi-account-multiple-check-outline": mdiAccountMultipleCheckOutline,
  "mdi-account-multiple-outline": mdiAccountMultipleOutline,
  "mdi-account-outline": mdiAccountOutline,
  "mdi-account-plus": mdiAccountPlus,
  "mdi-account-plus-outline": mdiAccountPlusOutline,
  "mdi-account-question-outline": mdiAccountQuestionOutline,
  "mdi-account-tie": mdiAccountTie,
  "mdi-account-voice": mdiAccountVoice,
  "mdi-alert-circle": mdiAlertCircle,
  "mdi-alert-decagram": mdiAlertDecagram,
  "mdi-alert-decagram-outline": mdiAlertDecagramOutline,
  "mdi-api": mdiApi,
  "mdi-apple-keyboard-command": mdiAppleKeyboardCommand,
  "mdi-apple-keyboard-control": mdiAppleKeyboardControl,
  "mdi-apple-keyboard-option": mdiAppleKeyboardOption,
  "mdi-apple-keyboard-shift": mdiAppleKeyboardShift,
  "mdi-arrow-down": mdiArrowDown,
  "mdi-arrow-down-bold": mdiArrowDownBold,
  "mdi-arrow-left": mdiArrowLeft,
  "mdi-arrow-right": mdiArrowRight,
  "mdi-arrow-top-right": mdiArrowTopRight,
  "mdi-arrow-up": mdiArrowUp,
  "mdi-arrow-up-bold": mdiArrowUpBold,
  "mdi-backspace": mdiBackspace,
  "mdi-basketball": mdiBasketball,
  "mdi-bell-outline": mdiBellOutline,
  "mdi-bell-plus-outline": mdiBellPlusOutline,
  "mdi-bell-ring": mdiBellRing,
  "mdi-book-open-outline": mdiBookOpenOutline,
  "mdi-book-open-page-variant": mdiBookOpenPageVariant,
  "mdi-book-open-page-variant-outline": mdiBookOpenPageVariantOutline,
  "mdi-briefcase-account-outline": mdiBriefcaseAccountOutline,
  "mdi-briefcase-outline": mdiBriefcaseOutline,
  "mdi-briefcase-search": mdiBriefcaseSearch,
  "mdi-briefcase-search-outline": mdiBriefcaseSearchOutline,
  "mdi-briefcase-variant": mdiBriefcaseVariant,
  "mdi-bug-outline": mdiBugOutline,
  "mdi-bullhorn": mdiBullhorn,
  "mdi-bullhorn-outline": mdiBullhornOutline,
  "mdi-cached": mdiCached,
  "mdi-calendar": mdiCalendar,
  "mdi-calendar-blank": mdiCalendarBlank,
  "mdi-calendar-check": mdiCalendarCheck,
  "mdi-calendar-clock": mdiCalendarClock,
  "mdi-calendar-start": mdiCalendarStart,
  "mdi-card-account-details-outline": mdiCardAccountDetailsOutline,
  "mdi-cart": mdiCart,
  "mdi-cart-outline": mdiCartOutline,
  "mdi-cart-off": mdiCartOff,
  "mdi-cash-multiple": mdiCashMultiple,
  "mdi-cash-sync": mdiCashSync,
  "mdi-certificate-outline": mdiCertificateOutline,
  "mdi-chart-areaspline": mdiChartAreaspline,
  "mdi-chart-bell-curve": mdiChartBellCurve,
  "mdi-chart-box-outline": mdiChartBoxOutline,
  "mdi-chart-line-variant": mdiChartLineVariant,
  "mdi-chart-timeline-variant": mdiChartTimelineVariant,
  "mdi-chat-outline": mdiChatOutline,
  "mdi-chat-processing-outline": mdiChatProcessingOutline,
  "mdi-check": mdiCheck,
  "mdi-check-circle": mdiCheckCircle,
  "mdi-check-circle-outline": mdiCheckCircleOutline,
  "mdi-check-decagram": mdiCheckDecagram,
  "mdi-checkbox-blank-circle-outline": mdiCheckboxBlankCircleOutline,
  "mdi-checkbox-blank-outline": mdiCheckboxBlankOutline,
  "mdi-checkbox-marked": mdiCheckboxMarked,
  "mdi-checkbox-marked-circle-outline": mdiCheckboxMarkedCircleOutline,
  "mdi-chevron-down": mdiChevronDown,
  "mdi-chevron-left": mdiChevronLeft,
  "mdi-chevron-right": mdiChevronRight,
  "mdi-chevron-up": mdiChevronUp,
  "mdi-circle": mdiCircle,
  "mdi-clipboard-check": mdiClipboardCheck,
  "mdi-clipboard-check-outline": mdiClipboardCheckOutline,
  "mdi-clipboard-plus": mdiClipboardPlus,
  "mdi-clipboard-text": mdiClipboardText,
  "mdi-clipboard-text-clock-outline": mdiClipboardTextClockOutline,
  "mdi-clipboard-text-outline": mdiClipboardTextOutline,
  "mdi-clock-fast": mdiClockFast,
  "mdi-clock-outline": mdiClockOutline,
  "mdi-close": mdiClose,
  "mdi-close-circle": mdiCloseCircle,
  "mdi-cloud-upload": mdiCloudUpload,
  "mdi-cog-outline": mdiCogOutline,
  "mdi-compass-outline": mdiCompassOutline,
  "mdi-connection": mdiConnection,
  "mdi-content-save": mdiContentSave,
  "mdi-content-save-outline": mdiContentSaveOutline,
  "mdi-controller-classic-outline": mdiControllerClassicOutline,
  "mdi-credit-card-check-outline": mdiCreditCardCheckOutline,
  "mdi-credit-card-sync": mdiCreditCardSync,
  "mdi-crop-square": mdiCropSquare,
  "mdi-currency-usd": mdiCurrencyUsd,
  "mdi-database": mdiDatabase,
  "mdi-database-outline": mdiDatabaseOutline,
  "mdi-delete": mdiDelete,
  "mdi-delete-outline": mdiDeleteOutline,
  "mdi-domain": mdiDomain,
  "mdi-dots-grid": mdiDotsGrid,
  "mdi-dots-horizontal": mdiDotsHorizontal,
  "mdi-dots-vertical": mdiDotsVertical,
  "mdi-download": mdiDownload,
  "mdi-earth": mdiEarth,
  "mdi-earth-plus": mdiEarthPlus,
  "mdi-email": mdiEmail,
  "mdi-email-edit-outline": mdiEmailEditOutline,
  "mdi-email-outline": mdiEmailOutline,
  "mdi-emoticon-happy-outline": mdiEmoticonHappyOutline,
  "mdi-emoticon-sad-outline": mdiEmoticonSadOutline,
  "mdi-eye": mdiEye,
  "mdi-eye-check-outline": mdiEyeCheckOutline,
  "mdi-eye-off": mdiEyeOff,
  "mdi-eye-outline": mdiEyeOutline,
  "mdi-eyedropper": mdiEyedropper,
  "mdi-facebook-messenger": mdiFacebookMessenger,
  "mdi-file-chart": mdiFileChart,
  "mdi-file-document": mdiFileDocument,
  "mdi-file-document-edit": mdiFileDocumentEdit,
  "mdi-file-document-edit-outline": mdiFileDocumentEditOutline,
  "mdi-file-document-outline": mdiFileDocumentOutline,
  "mdi-file-download-outline": mdiFileDownloadOutline,
  "mdi-filmstrip-box-multiple": mdiFilmstripBoxMultiple,
  "mdi-flag": mdiFlag,
  "mdi-flag-checkered": mdiFlagCheckered,
  "mdi-flag-outline": mdiFlagOutline,
  "mdi-flag-variant-outline": mdiFlagVariantOutline,
  "mdi-flash": mdiFlash,
  "mdi-folder-account": mdiFolderAccount,
  "mdi-format-align-justify": mdiFormatAlignJustify,
  "mdi-format-list-checks": mdiFormatListChecks,
  "mdi-forum-outline": mdiForumOutline,
  "mdi-fullscreen": mdiFullscreen,
  "mdi-fullscreen-exit": mdiFullscreenExit,
  "mdi-gamepad-variant-outline": mdiGamepadVariantOutline,
  "mdi-gavel": mdiGavel,
  "mdi-github": mdiGithub,
  "mdi-google": mdiGoogle,
  "mdi-history": mdiHistory,
  "mdi-home-map-marker": mdiHomeMapMarker,
  "mdi-image-filter-hdr": mdiImageFilterHdr,
  "mdi-image-multiple": mdiImageMultiple,
  "mdi-image-multiple-outline": mdiImageMultipleOutline,
  "mdi-image-outline": mdiImageOutline,
  "mdi-information": mdiInformation,
  "mdi-information-outline": mdiInformationOutline,
  "mdi-keyboard-return": mdiKeyboardReturn,
  "mdi-keyboard-space": mdiKeyboardSpace,
  "mdi-key-variant": mdiKeyVariant,
  "mdi-label-outline": mdiLabelOutline,
  "mdi-lifebuoy": mdiLifebuoy,
  "mdi-lightbulb-on-outline": mdiLightbulbOnOutline,
  "mdi-lightning-bolt": mdiLightningBolt,
  "mdi-link-variant": mdiLinkVariant,
  "mdi-linkedin": mdiLinkedin,
  "mdi-loading": mdiLoading,
  "mdi-lock": mdiLock,
  "mdi-login": mdiLogin,
  "mdi-logout": mdiLogout,
  "mdi-magnify": mdiMagnify,
  "mdi-map-marker": mdiMapMarker,
  "mdi-map-marker-outline": mdiMapMarkerOutline,
  "mdi-menu": mdiMenu,
  "mdi-menu-down": mdiMenuDown,
  "mdi-menu-right": mdiMenuRight,
  "mdi-message": mdiMessage,
  "mdi-message-text-outline": mdiMessageTextOutline,
  "mdi-message-outline": mdiMessageOutline,
  "mdi-message-plus-outline": mdiMessagePlusOutline,
  "mdi-message-processing-outline": mdiMessageProcessingOutline,
  "mdi-message-reply-text": mdiMessageReplyText,
  "mdi-microphone": mdiMicrophone,
  "mdi-microsoft": mdiMicrosoft,
  "mdi-minus": mdiMinus,
  "mdi-minus-box": mdiMinusBox,
  "mdi-monitor-dashboard": mdiMonitorDashboard,
  "mdi-movie-play-outline": mdiMoviePlayOutline,
  "mdi-open-in-new": mdiOpenInNew,
  "mdi-page-first": mdiPageFirst,
  "mdi-page-last": mdiPageLast,
  "mdi-palette": mdiPalette,
  "mdi-palette-outline": mdiPaletteOutline,
  "mdi-paperclip": mdiPaperclip,
  "mdi-pause": mdiPause,
  "mdi-pencil": mdiPencil,
  "mdi-pencil-outline": mdiPencilOutline,
  "mdi-play": mdiPlay,
  "mdi-play-circle": mdiPlayCircle,
  "mdi-play-circle-outline": mdiPlayCircleOutline,
  "mdi-playlist-edit": mdiPlaylistEdit,
  "mdi-playlist-plus": mdiPlaylistPlus,
  "mdi-plus": mdiPlus,
  "mdi-post-outline": mdiPostOutline,
  "mdi-progress-clock": mdiProgressClock,
  "mdi-radar": mdiRadar,
  "mdi-radiobox-blank": mdiRadioboxBlank,
  "mdi-radiobox-marked": mdiRadioboxMarked,
  "mdi-refresh": mdiRefresh,
  "mdi-reload": mdiReload,
  "mdi-restore": mdiRestore,
  "mdi-rhombus-medium": mdiRhombusMedium,
  "mdi-robot-happy-outline": mdiRobotHappyOutline,
  "mdi-robot-outline": mdiRobotOutline,
  "mdi-rocket-launch-outline": mdiRocketLaunchOutline,
  "mdi-school-outline": mdiSchoolOutline,
  "mdi-script-text-play-outline": mdiScriptTextPlayOutline,
  "mdi-send": mdiSend,
  "mdi-shape-outline": mdiShapeOutline,
  "mdi-share-outline": mdiShareOutline,
  "mdi-shield-account": mdiShieldAccount,
  "mdi-shield-account-outline": mdiShieldAccountOutline,
  "mdi-shield-alert": mdiShieldAlert,
  "mdi-shield-check": mdiShieldCheck,
  "mdi-shield-check-outline": mdiShieldCheckOutline,
  "mdi-shield-crown": mdiShieldCrown,
  "mdi-shield-key": mdiShieldKey,
  "mdi-shield-lock": mdiShieldLock,
  "mdi-shopping-outline": mdiShoppingOutline,
  "mdi-shopping-search": mdiShoppingSearch,
  "mdi-speedometer": mdiSpeedometer,
  "mdi-speedometer-medium": mdiSpeedometerMedium,
  "mdi-square-edit-outline": mdiSquareEditOutline,
  "mdi-star": mdiStar,
  "mdi-star-half-full": mdiStarHalfFull,
  "mdi-star-outline": mdiStarOutline,
  "mdi-store-outline": mdiStoreOutline,
  "mdi-storefront-outline": mdiStorefrontOutline,
  "mdi-subdirectory-arrow-right": mdiSubdirectoryArrowRight,
  "mdi-svg": mdiSvg,
  "mdi-table-arrow-down": mdiTableArrowDown,
  "mdi-tag": mdiTag,
  "mdi-tag-multiple-outline": mdiTagMultipleOutline,
  "mdi-target": mdiTarget,
  "mdi-text-box-edit-outline": mdiTextBoxEditOutline,
  "mdi-text-box-multiple": mdiTextBoxMultiple,
  "mdi-text-box-outline": mdiTextBoxOutline,
  "mdi-theme-light-dark": mdiThemeLightDark,
  "mdi-thumb-up-outline": mdiThumbUpOutline,
  "mdi-timeline-clock-outline": mdiTimelineClockOutline,
  "mdi-timer-off": mdiTimerOff,
  "mdi-timer-sand": mdiTimerSand,
  "mdi-tools": mdiTools,
  "mdi-transit-connection": mdiTransitConnection,
  "mdi-trophy-outline": mdiTrophyOutline,
  "mdi-tune": mdiTune,
  "mdi-twitter": mdiTwitter,
  "mdi-unfold-more-horizontal": mdiUnfoldMoreHorizontal,
  "mdi-update": mdiUpdate,
  "mdi-video": mdiVideo,
  "mdi-view-dashboard-outline": mdiViewDashboardOutline,
  "mdi-view-grid-outline": mdiViewGridOutline,
  "mdi-volume-high": mdiVolumeHigh,
  "mdi-volume-low": mdiVolumeLow,
  "mdi-volume-medium": mdiVolumeMedium,
  "mdi-volume-variant-off": mdiVolumeVariantOff,
  "mdi-weather-night": mdiWeatherNight,
  "mdi-weather-sunny": mdiWeatherSunny,
  "mdi-whatsapp": mdiWhatsapp,
} as const;

export type ProjectMdiIconKey = keyof typeof projectMdiIcons;
